server:
    http_listen_port: 9080
    grpc_listen_port: 0

positions:
    filename: /tmp/positions.yaml

clients:
    - url: http://loki:3100/loki/api/v1/push

scrape_configs:
    - job_name: app
      pipeline_stages:
          - json:
                expressions:
                    name: name
                    hostname: hostname
                    pid: pid
                    level: level
                    timestamp: time
          - labels:
                name:
                hostname:
                pid:
                level:
          - timestamp:
                source: timestamp
                format: RFC3339
      static_configs:
          - targets:
                - localhost
            labels:
                job: app
                __path__: /var/log/app.log
